version: '3'

services:
  redis:
    restart: always
    image: redis
    container_name: "redis"
    expose:
      - "6379"
  db:
    image: postgres
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  web:
    build: .
    image: icecream
    env_file: .env


    command: bash -c "gunicorn --workers=2  'manage:wsgi_app()' --bind :8000"


    container_name: "icecream"
    volumes:
      - .:/icecream
      - ./ICECREAM/static:/static
      - ./statics/media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "3000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./statics/media:/api/media
    depends_on:
      - web
  migration:
    image: icecream
    command: bash -c "alembic upgrade head"
    volumes:
      - .:/icecream
    depends_on:
      - db
volumes:
  postgres_data: